import type { Metadata } from "next";
import "../../styles/globals.css";
import { Cairo } from "next/font/google";
import { Cairo as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import HRSidebar from "@/components/layouts/hr-sidebar";
import DashboardNavbar from "@/components/layouts/dashboardNavbar";
import BlueCardHeader from "@/components/blueCardHeader";

export const metadata: Metadata = {
  title: "GDG Algiers",
  description: "Generated by create next app",
};

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("flex bg-background font-sans", fontSans.variable)}>
        <HRSidebar />
        <div className="flex flex-col w-full min-h-screen">
          <DashboardNavbar />
          <div className="flex-1 overflow-y-auto bg-black/5 p-[20px] h-screen">
            <BlueCardHeader />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
